<!DOCTYPE html>  
<html lang="en">  
    <head>
        <meta charset="UTF-8">
        <title>Goldeneye</title>
    </head>
    <body>
        <h1>Goldeneye</h1>
        <h2>Email Creator</h2>
        <p>Please, fill the following form in order to receive a company email address.</p>
        <form>
            <label for="name">Name:</label>
            <input type="text" id="name">
            <label for="surname">Surname:</label>
            <input type="text" id="surname">
            <select>
                <option value="milan">Milan</option>
                <option value="spain">Spain</option>
                <option value="new_york">New York</option>
            </select>
            <select>
                <option value="design">Design</option>
                <option value="business">Business</option>
                <option value="advertising">Advertising</option>
                <option value="research_development">Research & development</option>
            </select>
            <button>Send</button>
        /form>

    </body>
</html>